export const FETCH_URL_REQUEST = 'FETCH_URL_REQUEST'
export const FETCH_URL_SUCCESS = 'FETCH_URL_SUCCESS'
export const FETCH_URL_FAILURE = 'FETCH_URL_FAILURE'
export const LOAD_LOCAL_STORAGE = 'LOAD_LOCAL_STORAGE'
